name: Build mbed-edge-devmode-test
description: Build mbed-edge in developer mode

inputs:
  dockerfile:
    description: Usually "./Dockerfile"
    required: false
    default: "./Dockerfile"
  context:
    description: Usually dot '.'
    required: false
    default: "."
  configfiles:
    description: The folder to use under .github/edge-config for config files
    required: true
    default: "build-mbed-edge-devmode-test"    
  options:
    description: Additional options to pass to docker run
    required: false
    default: ''

outputs:
  cid:
    description: Container ID
    value: ${{ steps.info.outputs.cid }}

runs:
  using: composite
  steps:
    - name: Setup-Build-Files
      shell: bash
      run: |
        cd ${{ inputs.context }}
        cp -a .github/edge-config/${{ inputs.configfiles }}/* config
    - name: Run
      shell: bash
      run: |
        cd ${{ inputs.context }}
        docker build ${{ inputs.options }} -f ${{ inputs.dockerfile }} .