# Stage 1: Build the application
FROM debian:bookworm-slim AS builder

ARG developer_certificate=./config/mbed_cloud_dev_credentials.c
ARG update_certificate=./config/update_default_resources.c

# Set the working directory
WORKDIR /usr/src/app/mbed-edge

# Install dependencies in a single step to reduce layers
RUN apt-get update && \
    DEBIAN_FRONTEND="noninteractive" apt-get install -y --no-install-recommends \
    tzdata build-essential libc6-dev cmake && \
    rm -rf /var/lib/apt/lists/*

# Copy source files after dependencies are installed
COPY . .

# Return to main project and ensure it links with libbsd
WORKDIR /usr/src/app/mbed-edge
RUN mkdir -p build && cd build && \
    cmake -DDEVELOPER_MODE=ON \
    -DFIRMWARE_UPDATE=ON \
    -DTRACE_LEVEL=DEBUG \
    .. && \
    make

# Stage 2: Create a minimal runtime image
FROM debian:bookworm-slim

# Set working directory
WORKDIR /usr/src/app/mbed-edge

# Install only the required runtime dependencies
RUN apt-get update && \
    DEBIAN_FRONTEND="noninteractive" apt-get install -y --no-install-recommends \
    tzdata libc6 && \
    rm -rf /var/lib/apt/lists/*

# Copy only the built binary from the builder stage
COPY --from=builder /usr/src/app/mbed-edge/build/ /usr/src/app/mbed-edge/build/

CMD [ "./build/bin/edge-core", "--http-port", "8080", "--edge-pt-domain-socket", "/tmp/edge.sock" ]
