#ifndef _TEST_FOTA_CONF
#define _TEST_FOTA_CONF

#define DUMMY_BINARY_LOCATION ""
#define VENDOR_ID "SUBDEVICE-VENDOR"
#define CLASS_ID "SUBDEVICE--CLASS"
#define FIRMWARE_VERSION 1000
#define PAYLOAD_SIZE 100000
#define COMPONENT_NAME "MAIN"
#endif