
#ifndef __PT_SUBDEV_CONFIG_H__
#define __PT_SUBDEV_CONFIG_H__

#define COMPONENT_NAME_STR "MAIN"
#define VERSION_NAME_STR "0.0.0"
#define MANIFEST_VENDOR_STR "SUBDEVICE-VENDOR"
#define MANIFEST_VENDOR_STR_SIZE strlen(MANIFEST_VENDOR_STR)
#define MANIFEST_CLASS_STR "SUBDEVICE--CLASS"
#define MANIFEST_CLASS_STR_SIZE strlen(MANIFEST_CLASS_STR)

#endif      // __PT_SUBDEV_CONFIG_H__
