# SPDX-License-Identifier: Apache-2.0
file(MAKE_DIRECTORY "${WORK}")
execute_process(COMMAND "${FIXTURE}" --write-fixture "${WORK}/fixture.c" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Could not generate synthetic test credentials")
endif()
file(RENAME "${WORK}/fixture.c" "${WORK}/credentials café with spaces.c")
file(REMOVE "${WORK}/new bundle.cbor")
execute_process(COMMAND "${TOOL}" convert-developer --input "${WORK}/credentials café with spaces.c" --output "${WORK}/new bundle.cbor" RESULT_VARIABLE result)
if(NOT result EQUAL 0 OR NOT EXISTS "${WORK}/new bundle.cbor")
  message(FATAL_ERROR "Native CLI must accept arbitrary Unicode filenames")
endif()
file(SHA256 "${WORK}/new bundle.cbor" before)
execute_process(COMMAND "${TOOL}" convert-developer --input "${WORK}/credentials café with spaces.c" --output "${WORK}/new bundle.cbor" RESULT_VARIABLE result)
file(SHA256 "${WORK}/new bundle.cbor" after)
if(result EQUAL 0 OR NOT before STREQUAL after)
  message(FATAL_ERROR "Existing provisioning output must be preserved")
endif()
file(WRITE "${WORK}/malformed.c" "this is not a developer certificate")
file(REMOVE "${WORK}/malformed.cbor")
execute_process(COMMAND "${TOOL}" convert-developer --input "${WORK}/malformed.c" --output "${WORK}/malformed.cbor" RESULT_VARIABLE result)
if(result EQUAL 0 OR EXISTS "${WORK}/malformed.cbor")
  message(FATAL_ERROR "Invalid input must not create provisioning output")
endif()
