name: production build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        name: checkout repo
        with:
          submodules: recursive
      - name: Build devmode-test 
        uses: ./.github/actions/build-mbed-edge
        with:
          configfiles: "build-mbed-edge-devmode-test"