name: production build

on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  schedule:
    # Once week 03:26 on Saturday
    - cron: '26 3 * * Sat'

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: mbed-edge-test-build-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: [ "self-hosted", "client" ]
    env:
      SCRIPTS_INTERNAL_DIR: scripts-internal
      EDGE_CONFIGS_DIR: scripts-internal/edge/edge-config/build-mbed-edge-devmode-test
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v4
        name: checkout repo
        with:
          submodules: recursive
      - name: Check out scripts-internal repository code
        uses: actions/checkout@v4
        with:
          repository: PelionIoT/scripts-internal
          token: ${{ secrets.ACCESS_TOKEN }}
          path: ${{ env.SCRIPTS_INTERNAL_DIR }}
      - name: Build devmode-test 
        uses: ./.github/actions/build-mbed-edge
        with:
          configfiles:  ${{ env.EDGE_CONFIGS_DIR }}
      - name: Post status to Slack testing_builds
        if: always()
        uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          channel: '#testing_builds'
