name: production build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: [ "self-hosted", "edge-builder" ]

    steps:
      - uses: actions/checkout@v3
        name: checkout repo
        with:
          submodules: recursive

    # - uses: actions/checkout@v2
    #   name: checkout repo
    # >> By default, this action uses the Git context, so you don't need to use the actions/checkout action to check out the repository as this will be done directly by BuildKit.
    # See: https://github.com/docker/build-push-action/#usage

    # -
    #   name: Set up QEMU
    #   uses: docker/setup-qemu-action@v2
    # -
    #   name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2
    # -
    #   name: Login to GitHub Container Registry
    #   uses: docker/login-action@v2
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}
    # -
    #   name: Build and push
    #   uses: docker/build-push-action@v3
    #   with:
    #     push: true
    #     tags: izumanetworks/publicwebserver:staging
    #     network: host

      - name: Build devmode-test 
        uses: ./.github/actions/build-mbed-edge
        with:
          configfiles: "build-mbed-edge-devmode-test"
    # - name: Github Container Registry Build and push Docker image
    #   uses: pmorelli92/github-container-registry-build-push@2.0.0
    #   with:
    #       github-push-secret: ${{secrets.GITHUB_TOKEN}}
    #       docker-image-name: publicwebserver
    #       docker-image-tag: staging # optional
    #       # dockerfile-path: Dockerfile # optional
    #       # build-context: . # optional        


    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag publicwebserver:$(date +%s)
