name: misspell
on:
  push:
    paths-ignore:
      - 'lib/**'
  workflow_dispatch:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: mbed-edge-misspell-'${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  static-checks:
    runs-on: [ "self-hosted", "client" ]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Misspell
        uses: PelionIoT/actions/.github/actions/misspell@main
        with:
          exceptions: "mosquitto"
