name: PR-check unit tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: mbed-edge-test-valgrind-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:

  make-test-valgrind:

    runs-on: [ "self-hosted", "edge-builder" ]
    env:
      SCRIPTS_INTERNAL_DIR: scripts-internal
      EDGE_CONFIGS_DIR: scripts-internal/edge/edge-config/build-mbed-edge-devmode-test

    steps:
      - uses: actions/checkout@v3
        name: Checkout repo
        with:
          submodules: recursive
      - name: Check out scripts-internal repository code
        uses: actions/checkout@v3
        with:
          repository: PelionIoT/scripts-internal
          token: ${{ secrets.ACCESS_TOKEN }}
          path: ${{ env.SCRIPTS_INTERNAL_DIR }}
      - name: Run make -f Makefile.test
        uses: ./.github/actions/build-mbed-edge
        with:
          dockerfile:  ./Dockerfile.test
          configfiles:  ${{ env.EDGE_CONFIGS_DIR }}
